### PR TITLE
Remove unnecessary dir in path for PROJECT_FOLDER and DATA_FOLDER.

### PR DESCRIPTION
**Pull request by muraokamasaki**
Remove unnecessary directory `ir/` in path for PROJECT_FOLDER and DATA_FOLDER.

### CODE REVIEW

**Comment by matthew-z** [comment]
I want to find a way to set the path.
For example, read the root path from env variables?

**Comment by muraokamasaki** [comment]
Oh yeah i understand the problem with it.

For `PROJECT_FOLDER` it can just be a symbolic link right? since it is a module.
```
Path(__file__ + '/../..').resolve()
```
another alternative is to define it in the root folder of the module.

For `DATA_FOLDER`, env variable sounds alright since it is not a fixed location, with default being 1 dir above `PROJECT_FOLDER`.

What do you think

**Comment by matthew-z** [comment]
sounds good:


Project folder: relative path 
Data Folder: env variable

**Comment by matthew-z** [comment]
Thanks!

**Pull request merged**
